# SPDX-FileCopyrightText: 2021 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
name: Remove Labels

on: [issue_comment]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        if: |
          !startsWith(github.event.comment.body, 'This issue has been marked as "needs info" 4 weeks ago.') &&
            !startsWith(github.event.comment.body, 'This bug report did not receive an update in the last 4 weeks.') &&
            !contains(fromJSON('["camilasan", "i2h3", "mgallien", "nilsding", "Rello"]'), github.event.comment.user.login)
        with:
          labels: 'needs info'
          github_token: ${{ secrets.GITHUB_TOKEN }}
