# SPDX-FileCopyrightText: 2021 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
name: Remove needsinfo labels

on: [issue_comment]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        if: |
          github.event.comment.user.type !== "Bot" &&
            !contains(fromJSON('["camilasan", "i2h3", "mgallien", "nilsding", "Rello"]'), github.event.comment.user.login)
        with:
          labels: 'needs info'
          github_token: ${{ secrets.GITHUB_TOKEN }}
